In [1]:
import json
import uuid
from sqlalchemy import create_engine, inspect
from utils import reset_db, get_session, model_to_dict
from data.models import udahub

# Udahub Application

## Core Database

**Init DB**

In [2]:
udahub_db = "data/core/udahub.db"
reset_db(udahub_db)
engine = create_engine(f"sqlite:///{udahub_db}", echo=False)
udahub.Base.metadata.create_all(bind=engine)

2026-04-05 13:43:03,073 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-04-05 13:43:03,074 INFO sqlalchemy.engine.Engine COMMIT
✅ Recreated data/core/udahub.db with fresh schema

**Account**

In [3]:
account_id = "cultpass"
account_name = "CultPass Card"

with get_session(engine) as session:
    account = udahub.Account(
        account_id=account_id,
        account_name=account_name,
    )
    session.add(account)

---

## Integrations

**Use LLM to Generate Sample Data**

In [4]:
import os
import pandas as pd
import random
from dotenv import load_dotenv
from typing import List
from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any, Literal, TypedDict, Annotated
from langgraph.prebuilt import create_react_agent
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_core.prompts import PromptTemplate
from langchain_core.messages import SystemMessage
from langchain_chroma import Chroma
from langchain_core.documents import Document

load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
# llm_base_url = "https://openai.vocareum.com/v1"

llm = ChatOpenAI(
    model="gpt-4o",
    temperature=0.0,
    # base_url=llm_base_url,
    api_key=OPENAI_API_KEY,
)

embeddings_fn = OpenAIEmbeddings(
    model="text-embedding-3-large",
    # base_url=llm_base_url,
    api_key=OPENAI_API_KEY,
)

**Data Generation Parameters**

In [5]:
num_articles = 20
num_account = 10
num_user = 25
num_ticket = 50
num_msg = num_ticket
num_expected_tag_msg = round(num_msg * 0.8)
num_unexpected_tag_msg = num_msg - num_expected_tag_msg
chromadb_directory = "vectorstore"
collection_name = "knowledge_vecotr_store"

### Sampling Schema

For LLM to produce the data samples

In [6]:
class ArticlesSchema(BaseModel):
    title: Annotated[str, Field(description="Title of the article.")]
    content: Annotated[str, Field(description="Content of the article.")]
    tags: Annotated[str, Field(description="Tags of the article")]

class ArticlesListSchema(BaseModel):
    samples: Annotated[List[ArticlesSchema], Field(description="List of CultpassArticles")]

class AccountSamples(BaseModel):
    """Structured response for account table"""
    company_name: List[str] = Field(description="List of first name and last name")

class UsersSchema(BaseModel):
    name: Annotated[str, Field(description="User's name with first and last name.")]
    email: Annotated[str, Field(description="User's email address.")]
    is_blocked: Annotated[bool, Field(description="User's blocking status.")]
    account_id: Annotated[str, Field(description="Company account ID")]

class UsersListSchema(BaseModel):
    samples: Annotated[List[UsersSchema], Field(description="List of users")]

class SingleTicket(BaseModel):
    """Structured response for a ticket"""
    status: Annotated[Literal['open','pending','closed'], Field(description="Status of the ticket")]
    content: Annotated[str, Field(description="The ticket body message content.")]
    owner_id: Annotated[str, Field(description="User ID")]
    owner_name: Annotated[str, Field(description="User's name")]
    channel: Annotated[Literal['email','chat','web','sms','social','phone'], Field(description="Ticket priority")]
    tags: Annotated[str, Field(description="List of tags used for creating this message")]
    account_id: Annotated[str, Field(description="Company account ID")]
    urgency_score: Annotated[float, Field(description="Urgency of the ticket")]

class TicketSamples(BaseModel):
    """Structured response of ticket list"""
    samples: List[SingleTicket]

## Loading Default Data

* Knowledge Base
* Users Data

In [7]:
# Load Sample Articles
cultpass_articles = []
with open('data/external/cultpass_articles.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        cultpass_articles.append(json.loads(line))

# Extract Tags from Samples
sample_tags = [ article['tags'].split(', ') for article in cultpass_articles ]
sample_tags = set([ item for subtags in sample_tags for item in subtags ])
sample_tags_str = ", ".join(sample_tags)

# Define Tags with Expected Knowledge and Tags without Expected Knowledge
# (This is for sampling ticket questions "with vs without knowledge to answer" using LLM)
expected_tags = sample_tags
unexpected_tags = ['weather', 'stock price', 'dietary', 'health advice']

In [8]:
sample_tags

{'access',
 'attendance',
 'benefits',
 'billing',
 'booking',
 'cancelation',
 'escalation',
 'events',
 'login',
 'password',
 'pause',
 'pricing',
 'reservation',
 'subscription'}

In [9]:
# Load Users Data
cultpass_users = []
with open('data/external/cultpass_users.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        cultpass_users.append(json.loads(line))

#### Generate Knowledge Articles

In [ ]:
# Create Additional Knowledge Articles
num_cultpass_articles = len(cultpass_articles)
num_new_articles = num_articles - num_cultpass_articles
sample_articles_template = """
    You are an helpful expert creating sample of python sample article data based on given examples.  Do not provide any additional description or explanation.
    There is a mock-up project, it has the following description:

    You’ve joined a fast-growing AI startup building the next frontier in customer support automation. Your team is responsible for building UDA-Hub, 
    a Universal Decision Agent designed to plug into existing customer support systems (Zendesk, Intercom, Freshdesk, internal CRMs) and intelligently 
    resolve tickets. You need to generate sample knowledge articles in area including: {sample_tags}.  
    
    The knowledge areas given above will be used as tags for the generated articles.

    The first UDA-Hub customer Cultpass has the following sample articles to be used as knowledge to be used by the system:
    {samples}

    Cultpass is a online travel and leisure platform that provides a subscription-based card for travelers, offering access to airport lounges, travel discounts, 
    and exclusive experiences worldwide. Please create the new articles based on this context and the sample articles provided above.

    Provide {num_articles} more example like above and double check if all articles uses tags from {sample_tags}, if not try again.
    """

sample_articles_prompt = PromptTemplate(
    template = sample_articles_template,
    input_variables = ["samples","num_articles","sample_tags"],
    ).invoke({"samples": cultpass_articles,
              "num_articles": num_new_articles,
              "sample_tags": sample_tags}).to_messages()

new_cultpass_articles = llm.with_structured_output(ArticlesListSchema).invoke(sample_articles_prompt).model_dump()['samples']
cultpass_articles_ls = cultpass_articles + new_cultpass_articles

# Extracting Sample Tags for Each Sample
# new_sample_tags = [ article['tags'].split(', ') for article in cultpass_articles_ls ]
# new_sample_tags = set([ item for subtags in new_sample_tags for item in subtags ])
# new_sample_tags_str = ", ".join(new_sample_tags)

if len(cultpass_articles_ls) < 14:
    raise AssertionError("You should load the articles with at least 14 records")

In [11]:
cultpass_articles_ls

[{'title': 'How to Reserve a Spot for an Event',
  'content': 'If a user asks how to reserve an event:\n\n- Guide them to the CultPass app\n- Instruct them to browse the experience catalog and tap \'Reserve\'\n- If it\'s a premium or limited event, check if reservation confirmation is required via email\n- Remind them to arrive at least 15 minutes early with their QR code visible\n\n**Suggested phrasing:**\n"You can reserve an experience by opening the CultPass app, selecting your desired event, and tapping \'Reserve\'. Be sure to arrive 15 minutes early with your QR code ready."',
  'tags': 'reservation, events, booking, attendance'},
 {'title': "What's Included in a CultPass Subscription",
  'content': 'Each user is entitled to 4 cultural experiences per month, which may include:\n- Art exhibitions\n- Museum entries\n- Music concerts\n- Film screenings and more\n\nSome premium experiences may require an additional fee (visible in the app).\n\n**Suggested phrasing:**\n"Your CultPass subscription includes 4 curated experiences each month. You can choose from museums, concerts, film events and more. Premium events may have an extra cost, which is shown during reservation."',
  'tags': 'subscription, benefits, pricing, access'},
 {'title': 'How to Cancel or Pause a Subscription',
  'content': 'Users can manage their subscription via the app > \'My Account\' > \'Manage Plan\'.\n\n- Cancel: Effective at the end of the billing cycle\n- Pause: Preserves user data, resumes automatically when reactivated\n- Do NOT offer refunds unless approved by support lead\n\n**Suggested phrasing:**\n"You can cancel or pause your subscription at any time via the \'My Account\' section in the CultPass app. Cancelation takes effect at the end of your billing cycle."',
  'tags': 'cancelation, pause, subscription, billing'},
 {'title': 'How to Handle Login Issues?',
  'content': 'Most login issues are resolved with password reset:\n\n- Ask the user to tap \'Forgot Password\' on the login screen\n- Ensure they are using the correct registered email\n- If they did not receive the reset email, check spam folder or retry after 10 minutes\n- For persistent login issues, escalate to human support\n\n**Suggested phrasing:**\n"Try tapping \'Forgot Password\' on the login screen. Make sure you\'re using the email associated with your account. If the email doesn\'t arrive, check spam or try again in a few minutes."',
  'tags': 'login, password, access, escalation'},
 {'title': 'Understanding CultPass Pricing Plans',
  'content': 'CultPass offers flexible pricing plans to suit different needs:\n\n- Basic Plan: Access to 2 experiences per month\n- Premium Plan: Access to 5 experiences per month\n- Family Plan: Share with up to 4 family members\n\n**Suggested phrasing:**\n"CultPass offers various pricing plans, including Basic, Premium, and Family options, to cater to your cultural experience needs."',
  'tags': 'pricing, subscription, benefits'},
 {'title': 'How to Book a Cultural Experience',
  'content': 'Booking a cultural experience is simple:\n\n- Open the CultPass app\n- Browse the available experiences\n- Tap \'Book Now\' on your chosen event\n- Confirm your booking details\n\n**Suggested phrasing:**\n"To book an experience, open the CultPass app, select your event, and tap \'Book Now\'."',
  'tags': 'booking, reservation, events'},
 {'title': 'Managing Your CultPass Account',
  'content': 'To manage your account settings:\n\n- Go to \'My Account\' in the app\n- Update personal information, payment methods, and preferences\n- Contact support for any account-related issues\n\n**Suggested phrasing:**\n"Manage your CultPass account by navigating to \'My Account\' in the app to update your details."',
  'tags': 'access, subscription, billing'},
 {'title': 'How to Attend a CultPass Event',
  'content': 'Ensure a smooth event attendance:\n\n- Arrive 15 minutes early\n- Have your QR code ready for scanning\n- Follow any specific event instructions provided in the app\n\n**Suggested phrasing:**\n"Arrive early with your QR code ready to ensure a smooth entry to your CultPass event."',
  'tags': 'attendance, events, booking'},
 {'title': 'Steps to Reset Your CultPass Password',
  'content': 'Resetting your password is easy:\n\n- Tap \'Forgot Password\' on the login screen\n- Enter your registered email\n- Follow the instructions in the reset email\n\n**Suggested phrasing:**\n"If you need to reset your password, tap \'Forgot Password\' and follow the email instructions."',
  'tags': 'password, login, access'},
 {'title': 'How to Escalate a Support Ticket',
  'content': 'For unresolved issues, escalate your ticket:\n\n- Go to \'Support\' in the app\n- Select \'Escalate Ticket\'\n- Provide additional details if necessary\n\n**Suggested phrasing:**\n"If your issue isn\'t resolved, escalate your ticket through the \'Support\' section in the app."',
  'tags': 'escalation, support, access'},
 {'title': 'Understanding CultPass Event Benefits',
  'content': 'CultPass events offer unique benefits:\n\n- Exclusive access to cultural experiences\n- Discounts on premium events\n- Priority booking for popular events\n\n**Suggested phrasing:**\n"Enjoy exclusive access and discounts on CultPass events, with priority booking for popular experiences."',
  'tags': 'benefits, events, access'},
 {'title': 'How to Pause Your CultPass Subscription',
  'content': 'Pausing your subscription is straightforward:\n\n- Navigate to \'My Account\' > \'Manage Plan\'\n- Select \'Pause Subscription\'\n- Confirm your choice\n\n**Suggested phrasing:**\n"Pause your subscription anytime via \'My Account\' to temporarily halt your CultPass services."',
  'tags': 'pause, subscription, billing'},
 {'title': 'Resolving Billing Issues with CultPass',
  'content': 'For billing concerns:\n\n- Check your billing history in \'My Account\'\n- Contact support for discrepancies\n- Ensure payment methods are up-to-date\n\n**Suggested phrasing:**\n"For billing issues, review your history in \'My Account\' and contact support if needed."',
  'tags': 'billing, subscription, escalation'},
 {'title': 'How to Access CultPass Premium Events',
  'content': 'Accessing premium events is easy:\n\n- Open the CultPass app\n- Look for events marked \'Premium\'\n- Tap \'Access\' to view details and book\n\n**Suggested phrasing:**\n"Access premium events by selecting them in the app and tapping \'Access\' for more details."',
  'tags': 'access, events, booking'},
 {'title': 'Canceling a CultPass Event Reservation',
  'content': 'To cancel a reservation:\n\n- Go to \'My Reservations\' in the app\n- Select the event you wish to cancel\n- Tap \'Cancel Reservation\'\n\n**Suggested phrasing:**\n"Cancel your event reservation through \'My Reservations\' in the app."',
  'tags': 'cancelation, reservation, booking'},
 {'title': 'How to Update Your CultPass Payment Method',
  'content': 'Updating payment methods is simple:\n\n- Go to \'My Account\' > \'Payment Methods\'\n- Add or remove payment options\n- Ensure your default method is correct\n\n**Suggested phrasing:**\n"Update your payment methods in \'My Account\' to ensure seamless transactions."',
  'tags': 'billing, access, subscription'},
 {'title': 'Understanding CultPass Attendance Policies',
  'content': 'CultPass attendance policies include:\n\n- Arrive 15 minutes early\n- No-shows may affect future bookings\n- Follow event-specific guidelines\n\n**Suggested phrasing:**\n"Adhere to attendance policies by arriving early and following event guidelines."',
  'tags': 'attendance, events, booking'},
 {'title': 'How to Access CultPass Support',
  'content': 'Accessing support is easy:\n\n- Tap \'Support\' in the app\n- Browse FAQs or contact support directly\n- Use live chat for immediate assistance\n\n**Suggested phrasing:**\n"Access support through the app\'s \'Support\' section for FAQs or direct contact."',
  'tags': 'access, escalation, support'},
 {'title': 'CultPass Subscription Renewal Process',
  'content': 'Renewing your subscription is automatic:\n\n- Ensure payment methods are up-to-date\n- Check renewal dates in \'My Account\'\n- Contact support for manual renewals\n\n**Suggested phrasing:**\n"Your subscription renews automatically; ensure your payment details are current."',
  'tags': 'subscription, billing, access'},
 {'title': 'How to Benefit from CultPass Loyalty Program',
  'content': 'CultPass loyalty program offers:\n\n- Points for each event attended\n- Redeem points for discounts\n- Exclusive offers for loyal members\n\n**Suggested phrasing:**\n"Benefit from our loyalty program by attending events and redeeming points for discounts."',
  'tags': 'benefits, events, subscription'}]

Creating Vector Embedding for RAG

In [12]:
# Create vector store for knowledge articles
vector_store = Chroma(
    collection_name=collection_name,
    embedding_function=embeddings_fn,
    persist_directory=chromadb_directory,
)

cultpass_articles_docs = [ Document(page_content=article['title']+": "+article["content"],
                                      metadata={"tags": article['tags']},
                                      id=i) for i, article in enumerate(cultpass_articles_ls) ]
_ = vector_store.add_documents(documents=cultpass_articles_docs)

In [13]:
question = "Hi, I have a question regarding the billing for the events I attended last month. There seems to be a discrepancy in the charges, and I would like to understand the breakdown of the costs. Could you please provide a detailed billing statement? Thank you."
vector_store.similarity_search(question)

[Document(id='12', metadata={'tags': 'billing, subscription, escalation'}, page_content='Resolving Billing Issues with CultPass: For billing concerns:\n\n- Check your billing history in \'My Account\'\n- Contact support for discrepancies\n- Ensure payment methods are up-to-date\n\n**Suggested phrasing:**\n"For billing issues, review your history in \'My Account\' and contact support if needed."'),
 Document(id='1', metadata={'tags': 'subscription, benefits, pricing, access'}, page_content='What\'s Included in a CultPass Subscription: Each user is entitled to 4 cultural experiences per month, which may include:\n- Art exhibitions\n- Museum entries\n- Music concerts\n- Film screenings and more\n\nSome premium experiences may require an additional fee (visible in the app).\n\n**Suggested phrasing:**\n"Your CultPass subscription includes 4 curated experiences each month. You can choose from museums, concerts, film events and more. Premium events may have an extra cost, which is shown during reservation."'),
 Document(id='4', metadata={'tags': 'pricing, subscription, benefits'}, page_content='Understanding CultPass Pricing Plans: CultPass offers flexible pricing plans to suit different needs:\n\n- Basic Plan: Access to 2 experiences per month\n- Premium Plan: Access to 5 experiences per month\n- Family Plan: Share with up to 4 family members\n\n**Suggested phrasing:**\n"CultPass offers various pricing plans, including Basic, Premium, and Family options, to cater to your cultural experience needs."'),
 Document(id='0', metadata={'tags': 'reservation, events, booking, attendance'}, page_content='How to Reserve a Spot for an Event: If a user asks how to reserve an event:\n\n- Guide them to the CultPass app\n- Instruct them to browse the experience catalog and tap \'Reserve\'\n- If it\'s a premium or limited event, check if reservation confirmation is required via email\n- Remind them to arrive at least 15 minutes early with their QR code visible\n\n**Suggested phrasing:**\n"You can reserve an experience by opening the CultPass app, selecting your desired event, and tapping \'Reserve\'. Be sure to arrive 15 minutes early with your QR code ready."')]

#### Generate Users and Tickets

In [14]:
# Create Company List
account_prompt_template = """You are a company naming expert. Please come up with {num_account} company names."""

account_prompt = PromptTemplate(
    template = account_prompt_template,
    input_variables = ["num_account"],
    ).invoke({"num_account": num_account}).to_messages()

account = llm.with_structured_output(AccountSamples).invoke(account_prompt).model_dump()['company_name']
account_table = pd.DataFrame({"company_name": account})
# account_table['id'] = account_table.index
account_table['account_id'] = [ str(uuid.uuid4()) for i in range(num_account) ]
account_table_ls = account_table.to_dict(orient='records')
# account_table

In [15]:
# Create Additional Users
num_cultpass_users = len(cultpass_users)
num_new_users = num_user - num_cultpass_users
user_prompt_template = """
    You are a people naming expert. Please come up with {num_user} names with both first and last name.
    Randomly choose a company for each user from the account list and based on the name of the company,
    create an email address for this person.  Some companies should have more users than others.
    All users from the same company must have the same domain name on their email address.

    The `is_blocked` status should be randomly choosen as 'True' or 'False'

    List of account (companies): {account_table}"""

user_prompt = PromptTemplate(
    template = user_prompt_template,
    input_variables = ["num_user","account_table"],
    ).invoke({"num_user": num_new_users, "account_table": account_table}).to_messages()

user_ls = llm.with_structured_output(UsersListSchema).invoke(user_prompt).model_dump()['samples']
user_table = pd.DataFrame(user_ls)
user_table['id'] = [ str(uuid.uuid4().hex[:6]) for i in range(num_new_users) ]
user_table = user_table[['id', 'name', 'email', 'is_blocked','account_id']]
cultpass_users_table = pd.DataFrame(cultpass_users)
user_table = pd.concat([user_table, cultpass_users_table])
user_table['account_id'] = [ str(uuid.uuid4()) for i in range(num_user) ]     # account ID of LLM generated user should be replaced with true uuid4.

In [16]:
cultpass_users_table

       id            name                          email  is_blocked
0  a4ab87  Alice Kingsley  alice.kingsley@wonderland.com        True
1  f556c0       Bob Stone          bob.stone@granite.com       False
2  88382b     Cathy Bloom        cathy.bloom@florals.org       False
3  888fb2      David Noir      david.noir@shadowmail.com        True
4  f1f10d       Eva Green          eva.green@ecosoul.net       False
5  e6376d     Frank Ocean        frank.ocean@seawaves.io       False

In [17]:
user_table

,id,name,email,is_blocked,account_id
0,4e7472,Alice Johnson,alice.johnson@innovatechsolutions.com,False,7b27662a-1f61-4663-9bfa-6f39269a7ddb
1,2419e4,Bob Smith,bob.smith@ecospherenterprises.com,True,d6eaf64c-9f26-4c67-9918-c97f20330e86
2,a36f78,Charlie Brown,charlie.brown@quantumleapdynamics.com,False,4b932f2a-677d-4e77-97d1-c071bdb75016
3,9495bf,Diana Prince,diana.prince@greenwavetechnologies.com,True,7ef9b575-dc02-48ce-a78d-7fb8837ff1ab
4,a5819e,Ethan Hunt,ethan.hunt@stellarnexusinnovations.com,False,664a6666-dc03-4072-a458-f0ca3e28dd56
5,697a3f,Fiona Gallagher,fiona.gallagher@bluehorizonventures.com,True,251b2411-0560-4e0d-a440-f02d5394ce2b
6,95f808,George Clooney,george.clooney@pinnaclepeakpartners.com,False,0ddabea8-4ba1-4982-b346-c605e6444e4f
7,2bf6db,Hannah Montana,hannah.montana@synergyfusiongroup.com,True,26e0c69d-0779-4014-b9c1-100f60d27ac8
8,021efd,Ian McKellen,ian.mckellen@vanguardvisionaries.com,False,635577fd-ecfe-4ff8-a72b-b3e59b30f5ce
9,2e8369,Jessica Alba,jessica.alba@luminacorecreations.com,True,c84a759d-1c47-40c2-be90-75edef2092b4
10,0bd8c4,Kevin Hart,kevin.hart@innovatechsolutions.com,False,9c0ff72b-a651-4900-a3df-0562bb077eb7
11,8a8c81,Laura Linney,laura.linney@ecospherenterprises.com,True,c0f78c0e-13ae-414f-b8be-058208864426
12,b1ae04,Michael Jordan,michael.jordan@quantumleapdynamics.com,False,f6fae971-94ef-4577-9327-0b645ea7a577
13,3ae8f1,Natalie Portman,natalie.portman@greenwavetechnologies.com,True,dc2ebb67-26d3-4fe9-8277-b2f0488402f3
14,59edb1,Oscar Isaac,oscar.isaac@stellarnexusinnovations.com,False,2519e41d-88ef-4772-996e-723b93e63ecd
15,6e636f,Penelope Cruz,penelope.cruz@bluehorizonventures.com,True,797faa2f-7444-4a01-867c-de7cdf30446a
16,d42749,Quentin Tarantino,quentin.tarantino@pinnaclepeakpartners.com,False,d73380dd-efa5-4b96-8c69-878229f31ee5
17,e57d5b,Rachel McAdams,rachel.mcadams@synergyfusiongroup.com,True,fbcb5b61-caca-424a-b6bd-e3dc67b83759
18,4c83c6,Samuel L. Jackson,samuel.jackson@vanguardvisionaries.com,False,4cabbfb0-2e06-40b4-a158-e5072e766509
0,a4ab87,Alice Kingsley,alice.kingsley@wonderland.com,True,d8a96610-f8bc-4eeb-ad23-48650ed1d85c
1,f556c0,Bob Stone,bob.stone@granite.com,False,e8c8e4c7-51b0-4cca-abbe-543ddb497345
2,88382b,Cathy Bloom,cathy.bloom@florals.org,False,b57379ca-187e-441f-b495-96e2edb67429
3,888fb2,David Noir,david.noir@shadowmail.com,True,321ad39b-75d2-480b-8f91-463f83addd2e
4,f1f10d,Eva Green,eva.green@ecosoul.net,False,3b595166-b4e9-42c4-bd40-f943d6dfa7c6
5,e6376d,Frank Ocean,frank.ocean@seawaves.io,False,4bd1e79a-c7d3-4766-9700-fefc403c1906

In [18]:
# Random Combination of Tags
expected_list_min_expected_tag = 1
expected_list_max_expected_tag = 4
unexpected_list_min_expected_tag = 0
unexpected_list_max_expected_tag = 2
unexpected_list_min_unexpected_tag = 1
unexpected_list_max_unexpected_tag = 2

expected_tag_combination = [ random.sample(list(expected_tags), random.randint(expected_list_min_expected_tag,expected_list_max_expected_tag)) for i in range(num_expected_tag_msg) ]
unexpected_tag_combination = [ random.sample(list(expected_tags), random.randint(unexpected_list_min_expected_tag,unexpected_list_max_expected_tag)) +
                               random.sample(list(unexpected_tags), random.randint(unexpected_list_min_unexpected_tag,unexpected_list_max_unexpected_tag)) for i in range(num_unexpected_tag_msg) ]
tag_combination = expected_tag_combination + unexpected_tag_combination

In [19]:
# Create Tickets
ticket_prompt_template = """
    You are a IT ticket generation emulator focusing on generating the actual message of users.
    
    Step 1: Generate {num_ticket} tickets, 
        (a) Each `content` should be 20 to 200 words
        (b) Make occasional minor typos in the `content`
        (c) Each ticket `content` should be written based on the topic in the followin table:
        {tag_combination}  

    Step 2: For the `owner_id` (use `id` column in the table), `owner_name` (use `name` column in the table), account_id (`account_id`)
            and allow one user to have multiple tickets:
        {user_table}

    Step 3: Randomly selected a `channel` from ['email','chat','web','sms','social','phone'] for each ticket.
    """

ticket_prompt = PromptTemplate(
    template = ticket_prompt_template,
    input_variables = ["num_ticket","num_expected_tag_msg","num_unexpected_tag_msg","expected_tags","unexpected_tags","ticket_table"],
    ).invoke({"num_ticket": num_ticket,
              "tag_combination": tag_combination, 
              "unexpected_tags": unexpected_tags, 
              "user_table": user_table,
            }).to_messages()

ticket_ls = llm.with_structured_output(TicketSamples).invoke(ticket_prompt).model_dump()['samples']
ticket_table = pd.DataFrame(ticket_ls)
# ticket_table['id'] = msg_table.index
ticket_table['role'] = "user"
ticket_table['status'] = "open"
ticket_table['urgency_score'] = [random.random() for _ in range(num_ticket)]
# ticket_table

In [20]:
for ticket in ticket_table['content']:
    print(ticket)

Hi there, I am trying to book a flight through your website, but I keep getting an error message when I try to enter my payment details. I've tried multiple times and even used different browsers, but the issue persists. Could you please assist me with this? Thank you!
Hello, I forgot my password and am unable to access my account. I tried the 'forgot password' option, but I haven't received any reset email. Can you help me regain access to my account?
I need to escalate an issue regarding my hotel reservation. I was promised a sea view room, but upon arrival, I was given a standard room. This is not acceptable, and I would like this matter resolved immediately.
Hi, I am unable to access the premium features of my account even though I have a valid subscription. Could you please look into this and resolve the issue?
Hello, I am trying to pause my gym membership for a month due to personal reasons. However, I can't find the option to do so on your website. Can you guide me through the process?
I have a question regarding the attendance policy for the upcoming conference. Is it mandatory to attend all sessions, or can we choose specific ones?
Hi, I am trying to make a reservation at your restaurant, but the pricing seems to be different from what was advertised. Can you clarify the correct pricing for me?
I am interested in knowing more about the benefits included in the premium package. Could you provide me with detailed information?
Hello, I am trying to book tickets for an event, but the website keeps crashing. Is there an alternative way to book the tickets?
I am unable to log in to my account. I have tried resetting my password, but it still doesn't work. Can you help me resolve this issue?
Hi, I am considering upgrading my subscription, but I would like to know more about the benefits included in the higher tier. Can you provide me with more information?
I am trying to cancel my reservation, but the option is not available on the website. Can you assist me with the cancellation process?
Hello, I am having trouble with my subscription. I was charged twice for the same month. Can you look into this and refund the extra charge?
I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?
Hi, I am trying to log in to my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?
I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?
Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?
I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?
Hi, I am trying to access my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?
I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?
Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?
I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?
Hi, I am trying to log in to my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?
I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?
Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?
I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?
Hi, I am trying to log in to my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?
I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?
Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?
I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?
Hi, I am trying to log in to my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?
I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?
Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?
I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?
Hi, I am trying to log in to my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?
I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?
Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?
I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?
Hi, I am trying to log in to my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?
I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?
Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?
I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?
Hi, I am trying to log in to my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?
I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?
Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?
I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?
Hi, I am trying to log in to my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?
I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?
Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?
I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?

In [21]:
ticket_table

,status,content,owner_id,owner_name,channel,tags,account_id,urgency_score,role
0,open,"Hi there, I am trying to book a flight through...",4e7472,Alice Johnson,web,booking,7b27662a-1f61-4663-9bfa-6f39269a7ddb,0.691381,user
1,open,"Hello, I forgot my password and am unable to a...",2419e4,Bob Smith,email,password,d6eaf64c-9f26-4c67-9918-c97f20330e86,0.081610,user
2,open,I need to escalate an issue regarding my hotel...,a36f78,Charlie Brown,phone,escalation,4b932f2a-677d-4e77-97d1-c071bdb75016,0.151781,user
3,open,"Hi, I am unable to access the premium features...",9495bf,Diana Prince,chat,access,7ef9b575-dc02-48ce-a78d-7fb8837ff1ab,0.611700,user
4,open,"Hello, I am trying to pause my gym membership ...",a5819e,Ethan Hunt,web,pause,664a6666-dc03-4072-a458-f0ca3e28dd56,0.866805,user
5,open,I have a question regarding the attendance pol...,697a3f,Fiona Gallagher,email,attendance,251b2411-0560-4e0d-a440-f02d5394ce2b,0.895433,user
6,open,"Hi, I am trying to make a reservation at your ...",95f808,George Clooney,phone,reservation,0ddabea8-4ba1-4982-b346-c605e6444e4f,0.815664,user
7,open,I am interested in knowing more about the bene...,2bf6db,Hannah Montana,social,benefits,26e0c69d-0779-4014-b9c1-100f60d27ac8,0.601506,user
8,open,"Hello, I am trying to book tickets for an even...",021efd,Ian McKellen,web,booking,635577fd-ecfe-4ff8-a72b-b3e59b30f5ce,0.432368,user
9,open,I am unable to log in to my account. I have tr...,2e8369,Jessica Alba,email,login,c84a759d-1c47-40c2-be90-75edef2092b4,0.751701,user
10,open,"Hi, I am considering upgrading my subscription...",0bd8c4,Kevin Hart,chat,benefits,9c0ff72b-a651-4900-a3df-0562bb077eb7,0.724850,user
11,open,"I am trying to cancel my reservation, but the ...",8a8c81,Laura Linney,web,cancelation,c0f78c0e-13ae-414f-b8be-058208864426,0.781141,user
12,open,"Hello, I am having trouble with my subscriptio...",b1ae04,Michael Jordan,phone,subscription,f6fae971-94ef-4577-9327-0b645ea7a577,0.611535,user
13,open,I am unable to access the benefits section of ...,3ae8f1,Natalie Portman,email,benefits,dc2ebb67-26d3-4fe9-8277-b2f0488402f3,0.271750,user
14,open,"Hi, I am trying to log in to my account, but i...",59edb1,Oscar Isaac,chat,login,2519e41d-88ef-4772-996e-723b93e63ecd,0.938476,user
15,open,I am interested in attending the upcoming even...,6e636f,Penelope Cruz,social,events,797faa2f-7444-4a01-867c-de7cdf30446a,0.449893,user
16,open,"Hello, I am trying to book a hotel room, but t...",d42749,Quentin Tarantino,web,booking,d73380dd-efa5-4b96-8c69-878229f31ee5,0.187923,user
17,open,I am unable to access the benefits section of ...,e57d5b,Rachel McAdams,email,benefits,fbcb5b61-caca-424a-b6bd-e3dc67b83759,0.262252,user
18,open,"Hi, I am trying to access my account, but it s...",4c83c6,Samuel L. Jackson,chat,access,4cabbfb0-2e06-40b4-a158-e5072e766509,0.385274,user
19,open,I am interested in attending the upcoming even...,a4ab87,Alice Kingsley,social,events,d8a96610-f8bc-4eeb-ad23-48650ed1d85c,0.054081,user
20,open,"Hello, I am trying to book a hotel room, but t...",f556c0,Bob Stone,web,booking,e8c8e4c7-51b0-4cca-abbe-543ddb497345,0.683117,user
21,open,I am unable to access the benefits section of ...,88382b,Cathy Bloom,email,benefits,b57379ca-187e-441f-b495-96e2edb67429,0.063848,user
22,open,"Hi, I am trying to log in to my account, but i...",888fb2,David Noir,chat,login,321ad39b-75d2-480b-8f91-463f83addd2e,0.270267,user
23,open,I am interested in attending the upcoming even...,f1f10d,Eva Green,social,events,3b595166-b4e9-42c4-bd40-f943d6dfa7c6,0.842266,user
24,open,"Hello, I am trying to book a hotel room, but t...",e6376d,Frank Ocean,web,booking,4bd1e79a-c7d3-4766-9700-fefc403c1906,0.422633,user
25,open,I am unable to access the benefits section of ...,4e7472,Alice Johnson,email,benefits,7b27662a-1f61-4663-9bfa-6f39269a7ddb,0.515811,user
26,open,"Hi, I am trying to log in to my account, but i...",2419e4,Bob Smith,chat,login,d6eaf64c-9f26-4c67-9918-c97f20330e86,0.917178,user
27,open,I am interested in attending the upcoming even...,a36f78,Charlie Brown,social,events,4b932f2a-677d-4e77-97d1-c071bdb75016,0.755762,user
28,open,"Hello, I am trying to book a hotel room, but t...",9495bf,Diana Prince,web,booking,7ef9b575-dc02-48ce-a78d-7fb8837ff1ab,0.989862,user
29,open,I am unable to access the benefits section of ...,a5819e,Ethan Hunt,email,benefits,664a6666-dc03-4072-a458-f0ca3e28dd56,0.904726,user
30,open,"Hi, I am trying to log in to my account, but i...",697a3f,Fiona Gallagher,chat,login,251b2411-0560-4e0d-a440-f02d5394ce2b,0.178270,user
31,open,I am interested in attending the upcoming even...,95f808,George Clooney,social,events,0ddabea8-4ba1-4982-b346-c605e6444e4f,0.119260,user
32,open,"Hello, I am trying to book a hotel room, but t...",2bf6db,Hannah Montana,web,booking,26e0c69d-0779-4014-b9c1-100f60d27ac8,0.224255,user
33,open,I am unable to access the benefits section of ...,021efd,Ian McKellen,email,benefits,635577fd-ecfe-4ff8-a72b-b3e59b30f5ce,0.467117,user
34,open,"Hi, I am trying to log in to my account, but i...",2e8369,Jessica Alba,chat,login,c84a759d-1c47-40c2-be90-75edef2092b4,0.413751,user
35,open,I am interested in attending the upcoming even...,0bd8c4,Kevin Hart,social,events,9c0ff72b-a651-4900-a3df-0562bb077eb7,0.315911,user
36,open,"Hello, I am trying to book a hotel room, but t...",8a8c81,Laura Linney,web,booking,c0f78c0e-13ae-414f-b8be-058208864426,0.886841,user
37,open,I am unable to access the benefits section of ...,b1ae04,Michael Jordan,email,benefits,f6fae971-94ef-4577-9327-0b645ea7a577,0.418837,user
38,open,"Hi, I am trying to log in to my account, but i...",3ae8f1,Natalie Portman,chat,login,dc2ebb67-26d3-4fe9-8277-b2f0488402f3,0.490015,user
39,open,I am interested in attending the upcoming even...,59edb1,Oscar Isaac,social,events,2519e41d-88ef-4772-996e-723b93e63ecd,0.983369,user
40,open,"Hello, I am trying to book a hotel room, but t...",6e636f,Penelope Cruz,web,booking,797faa2f-7444-4a01-867c-de7cdf30446a,0.725668,user
41,open,I am unable to access the benefits section of ...,d42749,Quentin Tarantino,email,benefits,d73380dd-efa5-4b96-8c69-878229f31ee5,0.774358,user
42,open,"Hi, I am trying to log in to my account, but i...",e57d5b,Rachel McAdams,chat,login,fbcb5b61-caca-424a-b6bd-e3dc67b83759,0.899395,user
43,open,I am interested in attending the upcoming even...,4c83c6,Samuel L. Jackson,social,events,4cabbfb0-2e06-40b4-a158-e5072e766509,0.083858,user
44,open,"Hello, I am trying to book a hotel room, but t...",a4ab87,Alice Kingsley,web,booking,d8a96610-f8bc-4eeb-ad23-48650ed1d85c,0.524949,user
45,open,I am unable to access the benefits section of ...,f556c0,Bob Stone,email,benefits,e8c8e4c7-51b0-4cca-abbe-543ddb497345,0.862416,user
46,open,"Hi, I am trying to log in to my account, but i...",88382b,Cathy Bloom,chat,login,b57379ca-187e-441f-b495-96e2edb67429,0.044738,user
47,open,I am interested in attending the upcoming even...,888fb2,David Noir,social,events,321ad39b-75d2-480b-8f91-463f83addd2e,0.334315,user
48,open,"Hello, I am trying to book a hotel room, but t...",f1f10d,Eva Green,web,booking,3b595166-b4e9-42c4-bd40-f943d6dfa7c6,0.476423,user
49,open,I am unable to access the benefits section of ...,e6376d,Frank Ocean,email,benefits,4bd1e79a-c7d3-4766-9700-fefc403c1906,0.337482,user

In [22]:
len(ticket_table)

50

## Load Samples into Database

In [23]:
with get_session(engine) as session:
    kb = []
    for article in cultpass_articles:
        knowledge = udahub.Knowledge(
            article_id=str(uuid.uuid4()),
            account_id=account_id,
            title=article["title"],
            content=article["content"],
            tags=article["tags"]
        )
        kb.append(knowledge)
    session.add_all(kb)

**Ticket**

In [24]:
user_table.columns

Index(['id', 'name', 'email', 'is_blocked', 'account_id'], dtype='object')

In [25]:
def add_user(user_info):
    """
    Adding a single user to the database.
    """
    with get_session(engine) as session:
        user = udahub.User(
            user_id=user_info["account_id"],
            account_id=account_id,
            external_user_id=user_info["id"],
            user_name=user_info["name"],
            is_blocked=user_info["is_blocked"],
            email_address=user_info["email"]
            )
        session.add_all([user])

In [26]:
for index, row in user_table.iterrows():
    add_user(row)

In [ ]:
def add_ticket(ticket_info):
    """
    Adding a single ticket to the database
    """
    with get_session(engine) as session:
        user = session.query(udahub.User).filter_by(
            account_id=account_id,
            external_user_id=ticket_info["owner_id"],
        ).first()

        print(ticket_info)
        print(user)

        if not user:
            user = udahub.User(
                # user_id=str(uuid.uuid4()),
                user_id=ticket_info["account_id"],
                account_id=account_id,
                external_user_id=ticket_info["owner_id"],
                user_name=ticket_info["owner_name"],
                is_blocked=False,     # Data structure in data/models/udahub.py had been modified to include this flag for advanced agent capability
                email_address=None    # Data structure in data/models/udahub.py had been modified to include this flag for advanced agent capability
            )
        
        ticket = udahub.Ticket(
            ticket_id=str(uuid.uuid4()),
            account_id=account_id,
            user_id=user.user_id,
            channel=ticket_info["channel"],
        )
        metadata = udahub.TicketMetadata(
            ticket_id=ticket.ticket_id,
            status=ticket_info["status"],
            main_issue_type=None,
            tags=ticket_info["tags"],
            urgency_score=ticket_info["urgency_score"]
        )

        first_message = udahub.TicketMessage(
            message_id=str(uuid.uuid4()),
            ticket_id=ticket.ticket_id,
            role=ticket_info["role"],
            content=ticket_info["content"],
        )

        # print(user)
        session.add_all([user, ticket, metadata, first_message])

In [28]:
for index, row in ticket_table.iterrows():
    add_ticket(row)

status                                                        open
content          Hi there, I am trying to book a flight through...
owner_id                                                    4e7472
owner_name                                           Alice Johnson
channel                                                        web
tags                                                       booking
account_id                    7b27662a-1f61-4663-9bfa-6f39269a7ddb
urgency_score                                             0.691381
role                                                          user
Name: 0, dtype: object
<User(user_id='7b27662a-1f61-4663-9bfa-6f39269a7ddb', user_name='Alice Johnson', external_user_id='4e7472')>
status                                                        open
content          Hello, I forgot my password and am unable to a...
owner_id                                                    2419e4
owner_name                                               Bob Smith
channel                                                      email
tags                                                      password
account_id                    d6eaf64c-9f26-4c67-9918-c97f20330e86
urgency_score                                              0.08161
role                                                          user
Name: 1, dtype: object
<User(user_id='d6eaf64c-9f26-4c67-9918-c97f20330e86', user_name='Bob Smith', external_user_id='2419e4')>
status                                                        open
content          I need to escalate an issue regarding my hotel...
owner_id                                                    a36f78
owner_name                                           Charlie Brown
channel                                                      phone
tags                                                    escalation
account_id                    4b932f2a-677d-4e77-97d1-c071bdb75016
urgency_score                                             0.151781
role                                                          user
Name: 2, dtype: object
<User(user_id='4b932f2a-677d-4e77-97d1-c071bdb75016', user_name='Charlie Brown', external_user_id='a36f78')>
status                                                        open
content          Hi, I am unable to access the premium features...
owner_id                                                    9495bf
owner_name                                            Diana Prince
channel                                                       chat
tags                                                        access
account_id                    7ef9b575-dc02-48ce-a78d-7fb8837ff1ab
urgency_score                                               0.6117
role                                                          user
Name: 3, dtype: object
<User(user_id='7ef9b575-dc02-48ce-a78d-7fb8837ff1ab', user_name='Diana Prince', external_user_id='9495bf')>
status                                                        open
content          Hello, I am trying to pause my gym membership ...
owner_id                                                    a5819e
owner_name                                              Ethan Hunt
channel                                                        web
tags                                                         pause
account_id                    664a6666-dc03-4072-a458-f0ca3e28dd56
urgency_score                                             0.866805
role                                                          user
Name: 4, dtype: object
<User(user_id='664a6666-dc03-4072-a458-f0ca3e28dd56', user_name='Ethan Hunt', external_user_id='a5819e')>
status                                                        open
content          I have a question regarding the attendance pol...
owner_id                                                    697a3f
owner_name                                         Fiona Gallagher
channel                                                      email
tags                                                    attendance
account_id                    251b2411-0560-4e0d-a440-f02d5394ce2b
urgency_score                                             0.895433
role                                                          user
Name: 5, dtype: object
<User(user_id='251b2411-0560-4e0d-a440-f02d5394ce2b', user_name='Fiona Gallagher', external_user_id='697a3f')>
status                                                        open
content          Hi, I am trying to make a reservation at your ...
owner_id                                                    95f808
owner_name                                          George Clooney
channel                                                      phone
tags                                                   reservation
account_id                    0ddabea8-4ba1-4982-b346-c605e6444e4f
urgency_score                                             0.815664
role                                                          user
Name: 6, dtype: object
<User(user_id='0ddabea8-4ba1-4982-b346-c605e6444e4f', user_name='George Clooney', external_user_id='95f808')>
status                                                        open
content          I am interested in knowing more about the bene...
owner_id                                                    2bf6db
owner_name                                          Hannah Montana
channel                                                     social
tags                                                      benefits
account_id                    26e0c69d-0779-4014-b9c1-100f60d27ac8
urgency_score                                             0.601506
role                                                          user
Name: 7, dtype: object
<User(user_id='26e0c69d-0779-4014-b9c1-100f60d27ac8', user_name='Hannah Montana', external_user_id='2bf6db')>
status                                                        open
content          Hello, I am trying to book tickets for an even...
owner_id                                                    021efd
owner_name                                            Ian McKellen
channel                                                        web
tags                                                       booking
account_id                    635577fd-ecfe-4ff8-a72b-b3e59b30f5ce
urgency_score                                             0.432368
role                                                          user
Name: 8, dtype: object
<User(user_id='635577fd-ecfe-4ff8-a72b-b3e59b30f5ce', user_name='Ian McKellen', external_user_id='021efd')>
status                                                        open
content          I am unable to log in to my account. I have tr...
owner_id                                                    2e8369
owner_name                                            Jessica Alba
channel                                                      email
tags                                                         login
account_id                    c84a759d-1c47-40c2-be90-75edef2092b4
urgency_score                                             0.751701
role                                                          user
Name: 9, dtype: object
<User(user_id='c84a759d-1c47-40c2-be90-75edef2092b4', user_name='Jessica Alba', external_user_id='2e8369')>
status                                                        open
content          Hi, I am considering upgrading my subscription...
owner_id                                                    0bd8c4
owner_name                                              Kevin Hart
channel                                                       chat
tags                                                      benefits
account_id                    9c0ff72b-a651-4900-a3df-0562bb077eb7
urgency_score                                              0.72485
role                                                          user
Name: 10, dtype: object
<User(user_id='9c0ff72b-a651-4900-a3df-0562bb077eb7', user_name='Kevin Hart', external_user_id='0bd8c4')>
status                                                        open
content          I am trying to cancel my reservation, but the ...
owner_id                                                    8a8c81
owner_name                                            Laura Linney
channel                                                        web
tags                                                   cancelation
account_id                    c0f78c0e-13ae-414f-b8be-058208864426
urgency_score                                             0.781141
role                                                          user
Name: 11, dtype: object
<User(user_id='c0f78c0e-13ae-414f-b8be-058208864426', user_name='Laura Linney', external_user_id='8a8c81')>
status                                                        open
content          Hello, I am having trouble with my subscriptio...
owner_id                                                    b1ae04
owner_name                                          Michael Jordan
channel                                                      phone
tags                                                  subscription
account_id                    f6fae971-94ef-4577-9327-0b645ea7a577
urgency_score                                             0.611535
role                                                          user
Name: 12, dtype: object
<User(user_id='f6fae971-94ef-4577-9327-0b645ea7a577', user_name='Michael Jordan', external_user_id='b1ae04')>
status                                                        open
content          I am unable to access the benefits section of ...
owner_id                                                    3ae8f1
owner_name                                         Natalie Portman
channel                                                      email
tags                                                      benefits
account_id                    dc2ebb67-26d3-4fe9-8277-b2f0488402f3
urgency_score                                              0.27175
role                                                          user
Name: 13, dtype: object
<User(user_id='dc2ebb67-26d3-4fe9-8277-b2f0488402f3', user_name='Natalie Portman', external_user_id='3ae8f1')>
status                                                        open
content          Hi, I am trying to log in to my account, but i...
owner_id                                                    59edb1
owner_name                                             Oscar Isaac
channel                                                       chat
tags                                                         login
account_id                    2519e41d-88ef-4772-996e-723b93e63ecd
urgency_score                                             0.938476
role                                                          user
Name: 14, dtype: object
<User(user_id='2519e41d-88ef-4772-996e-723b93e63ecd', user_name='Oscar Isaac', external_user_id='59edb1')>
status                                                        open
content          I am interested in attending the upcoming even...
owner_id                                                    6e636f
owner_name                                           Penelope Cruz
channel                                                     social
tags                                                        events
account_id                    797faa2f-7444-4a01-867c-de7cdf30446a
urgency_score                                             0.449893
role                                                          user
Name: 15, dtype: object
<User(user_id='797faa2f-7444-4a01-867c-de7cdf30446a', user_name='Penelope Cruz', external_user_id='6e636f')>
status                                                        open
content          Hello, I am trying to book a hotel room, but t...
owner_id                                                    d42749
owner_name                                       Quentin Tarantino
channel                                                        web
tags                                                       booking
account_id                    d73380dd-efa5-4b96-8c69-878229f31ee5
urgency_score                                             0.187923
role                                                          user
Name: 16, dtype: object
<User(user_id='d73380dd-efa5-4b96-8c69-878229f31ee5', user_name='Quentin Tarantino', external_user_id='d42749')>
status                                                        open
content          I am unable to access the benefits section of ...
owner_id                                                    e57d5b
owner_name                                          Rachel McAdams
channel                                                      email
tags                                                      benefits
account_id                    fbcb5b61-caca-424a-b6bd-e3dc67b83759
urgency_score                                             0.262252
role                                                          user
Name: 17, dtype: object
<User(user_id='fbcb5b61-caca-424a-b6bd-e3dc67b83759', user_name='Rachel McAdams', external_user_id='e57d5b')>
status                                                        open
content          Hi, I am trying to access my account, but it s...
owner_id                                                    4c83c6
owner_name                                       Samuel L. Jackson
channel                                                       chat
tags                                                        access
account_id                    4cabbfb0-2e06-40b4-a158-e5072e766509
urgency_score                                             0.385274
role                                                          user
Name: 18, dtype: object
<User(user_id='4cabbfb0-2e06-40b4-a158-e5072e766509', user_name='Samuel L. Jackson', external_user_id='4c83c6')>
status                                                        open
content          I am interested in attending the upcoming even...
owner_id                                                    a4ab87
owner_name                                          Alice Kingsley
channel                                                     social
tags                                                        events
account_id                    d8a96610-f8bc-4eeb-ad23-48650ed1d85c
urgency_score                                             0.054081
role                                                          user
Name: 19, dtype: object
<User(user_id='d8a96610-f8bc-4eeb-ad23-48650ed1d85c', user_name='Alice Kingsley', external_user_id='a4ab87')>
status                                                        open
content          Hello, I am trying to book a hotel room, but t...
owner_id                                                    f556c0
owner_name                                               Bob Stone
channel                                                        web
tags                                                       booking
account_id                    e8c8e4c7-51b0-4cca-abbe-543ddb497345
urgency_score                                             0.683117
role                                                          user
Name: 20, dtype: object
<User(user_id='e8c8e4c7-51b0-4cca-abbe-543ddb497345', user_name='Bob Stone', external_user_id='f556c0')>
status                                                        open
content          I am unable to access the benefits section of ...
owner_id                                                    88382b
owner_name                                             Cathy Bloom
channel                                                      email
tags                                                      benefits
account_id                    b57379ca-187e-441f-b495-96e2edb67429
urgency_score                                             0.063848
role                                                          user
Name: 21, dtype: object
<User(user_id='b57379ca-187e-441f-b495-96e2edb67429', user_name='Cathy Bloom', external_user_id='88382b')>
status                                                        open
content          Hi, I am trying to log in to my account, but i...
owner_id                                                    888fb2
owner_name                                              David Noir
channel                                                       chat
tags                                                         login
account_id                    321ad39b-75d2-480b-8f91-463f83addd2e
urgency_score                                             0.270267
role                                                          user
Name: 22, dtype: object
<User(user_id='321ad39b-75d2-480b-8f91-463f83addd2e', user_name='David Noir', external_user_id='888fb2')>
status                                                        open
content          I am interested in attending the upcoming even...
owner_id                                                    f1f10d
owner_name                                               Eva Green
channel                                                     social
tags                                                        events
account_id                    3b595166-b4e9-42c4-bd40-f943d6dfa7c6
urgency_score                                             0.842266
role                                                          user
Name: 23, dtype: object
<User(user_id='3b595166-b4e9-42c4-bd40-f943d6dfa7c6', user_name='Eva Green', external_user_id='f1f10d')>
status                                                        open
content          Hello, I am trying to book a hotel room, but t...
owner_id                                                    e6376d
owner_name                                             Frank Ocean
channel                                                        web
tags                                                       booking
account_id                    4bd1e79a-c7d3-4766-9700-fefc403c1906
urgency_score                                             0.422633
role                                                          user
Name: 24, dtype: object
<User(user_id='4bd1e79a-c7d3-4766-9700-fefc403c1906', user_name='Frank Ocean', external_user_id='e6376d')>
status                                                        open
content          I am unable to access the benefits section of ...
owner_id                                                    4e7472
owner_name                                           Alice Johnson
channel                                                      email
tags                                                      benefits
account_id                    7b27662a-1f61-4663-9bfa-6f39269a7ddb
urgency_score                                             0.515811
role                                                          user
Name: 25, dtype: object
<User(user_id='7b27662a-1f61-4663-9bfa-6f39269a7ddb', user_name='Alice Johnson', external_user_id='4e7472')>
status                                                        open
content          Hi, I am trying to log in to my account, but i...
owner_id                                                    2419e4
owner_name                                               Bob Smith
channel                                                       chat
tags                                                         login
account_id                    d6eaf64c-9f26-4c67-9918-c97f20330e86
urgency_score                                             0.917178
role                                                          user
Name: 26, dtype: object
<User(user_id='d6eaf64c-9f26-4c67-9918-c97f20330e86', user_name='Bob Smith', external_user_id='2419e4')>
status                                                        open
content          I am interested in attending the upcoming even...

# Tests

In [29]:
with get_session(engine) as session:
    account = session.query(udahub.Account).filter_by(
        account_id=account_id
    ).first()
    print(account)

<Account(account_id='cultpass', account_name='CultPass Card')>

In [30]:
with get_session(engine) as session:
    account = session.query(udahub.Account).filter_by(
        account_id=account_id
    ).first()
    for article in account.knowledge_articles:
        print(article)

<Knowledge(article_id='b63de4ca-62c4-44d9-830f-4da76a641ff0', title='How to Reserve a Spot for an Event')>
<Knowledge(article_id='42adf8ce-70a9-4a4b-90d4-0671129f4be3', title='What's Included in a CultPass Subscription')>
<Knowledge(article_id='7041a61c-ef0b-4bdb-bdaa-1cfe6a841c91', title='How to Cancel or Pause a Subscription')>
<Knowledge(article_id='723d076f-370a-4265-b555-0cbae0206fb3', title='How to Handle Login Issues?')>

In [31]:
with get_session(engine) as session:
    users = session.query(udahub.User).all()
    for user in users:
        # Get all column names for this model
        inst = inspect(user)
        # Create a dictionary of {column_name: value}
        columns_data = {c.key: getattr(user, c.key) for c in inst.mapper.column_attrs}
        print(columns_data)

{'user_id': '7b27662a-1f61-4663-9bfa-6f39269a7ddb', 'account_id': 'cultpass', 'external_user_id': '4e7472', 'user_name': 'Alice Johnson', 'is_blocked': False, 'email_address': 'alice.johnson@innovatechsolutions.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': 'd6eaf64c-9f26-4c67-9918-c97f20330e86', 'account_id': 'cultpass', 'external_user_id': '2419e4', 'user_name': 'Bob Smith', 'is_blocked': True, 'email_address': 'bob.smith@ecospherenterprises.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': '4b932f2a-677d-4e77-97d1-c071bdb75016', 'account_id': 'cultpass', 'external_user_id': 'a36f78', 'user_name': 'Charlie Brown', 'is_blocked': False, 'email_address': 'charlie.brown@quantumleapdynamics.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': '7ef9b575-dc02-48ce-a78d-7fb8837ff1ab', 'account_id': 'cultpass', 'external_user_id': '9495bf', 'user_name': 'Diana Prince', 'is_blocked': True, 'email_address': 'diana.prince@greenwavetechnologies.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': '664a6666-dc03-4072-a458-f0ca3e28dd56', 'account_id': 'cultpass', 'external_user_id': 'a5819e', 'user_name': 'Ethan Hunt', 'is_blocked': False, 'email_address': 'ethan.hunt@stellarnexusinnovations.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': '251b2411-0560-4e0d-a440-f02d5394ce2b', 'account_id': 'cultpass', 'external_user_id': '697a3f', 'user_name': 'Fiona Gallagher', 'is_blocked': True, 'email_address': 'fiona.gallagher@bluehorizonventures.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': '0ddabea8-4ba1-4982-b346-c605e6444e4f', 'account_id': 'cultpass', 'external_user_id': '95f808', 'user_name': 'George Clooney', 'is_blocked': False, 'email_address': 'george.clooney@pinnaclepeakpartners.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': '26e0c69d-0779-4014-b9c1-100f60d27ac8', 'account_id': 'cultpass', 'external_user_id': '2bf6db', 'user_name': 'Hannah Montana', 'is_blocked': True, 'email_address': 'hannah.montana@synergyfusiongroup.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': '635577fd-ecfe-4ff8-a72b-b3e59b30f5ce', 'account_id': 'cultpass', 'external_user_id': '021efd', 'user_name': 'Ian McKellen', 'is_blocked': False, 'email_address': 'ian.mckellen@vanguardvisionaries.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': 'c84a759d-1c47-40c2-be90-75edef2092b4', 'account_id': 'cultpass', 'external_user_id': '2e8369', 'user_name': 'Jessica Alba', 'is_blocked': True, 'email_address': 'jessica.alba@luminacorecreations.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': '9c0ff72b-a651-4900-a3df-0562bb077eb7', 'account_id': 'cultpass', 'external_user_id': '0bd8c4', 'user_name': 'Kevin Hart', 'is_blocked': False, 'email_address': 'kevin.hart@innovatechsolutions.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': 'c0f78c0e-13ae-414f-b8be-058208864426', 'account_id': 'cultpass', 'external_user_id': '8a8c81', 'user_name': 'Laura Linney', 'is_blocked': True, 'email_address': 'laura.linney@ecospherenterprises.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': 'f6fae971-94ef-4577-9327-0b645ea7a577', 'account_id': 'cultpass', 'external_user_id': 'b1ae04', 'user_name': 'Michael Jordan', 'is_blocked': False, 'email_address': 'michael.jordan@quantumleapdynamics.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': 'dc2ebb67-26d3-4fe9-8277-b2f0488402f3', 'account_id': 'cultpass', 'external_user_id': '3ae8f1', 'user_name': 'Natalie Portman', 'is_blocked': True, 'email_address': 'natalie.portman@greenwavetechnologies.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': '2519e41d-88ef-4772-996e-723b93e63ecd', 'account_id': 'cultpass', 'external_user_id': '59edb1', 'user_name': 'Oscar Isaac', 'is_blocked': False, 'email_address': 'oscar.isaac@stellarnexusinnovations.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': '797faa2f-7444-4a01-867c-de7cdf30446a', 'account_id': 'cultpass', 'external_user_id': '6e636f', 'user_name': 'Penelope Cruz', 'is_blocked': True, 'email_address': 'penelope.cruz@bluehorizonventures.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': 'd73380dd-efa5-4b96-8c69-878229f31ee5', 'account_id': 'cultpass', 'external_user_id': 'd42749', 'user_name': 'Quentin Tarantino', 'is_blocked': False, 'email_address': 'quentin.tarantino@pinnaclepeakpartners.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': 'fbcb5b61-caca-424a-b6bd-e3dc67b83759', 'account_id': 'cultpass', 'external_user_id': 'e57d5b', 'user_name': 'Rachel McAdams', 'is_blocked': True, 'email_address': 'rachel.mcadams@synergyfusiongroup.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': '4cabbfb0-2e06-40b4-a158-e5072e766509', 'account_id': 'cultpass', 'external_user_id': '4c83c6', 'user_name': 'Samuel L. Jackson', 'is_blocked': False, 'email_address': 'samuel.jackson@vanguardvisionaries.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': 'd8a96610-f8bc-4eeb-ad23-48650ed1d85c', 'account_id': 'cultpass', 'external_user_id': 'a4ab87', 'user_name': 'Alice Kingsley', 'is_blocked': True, 'email_address': 'alice.kingsley@wonderland.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': 'e8c8e4c7-51b0-4cca-abbe-543ddb497345', 'account_id': 'cultpass', 'external_user_id': 'f556c0', 'user_name': 'Bob Stone', 'is_blocked': False, 'email_address': 'bob.stone@granite.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': 'b57379ca-187e-441f-b495-96e2edb67429', 'account_id': 'cultpass', 'external_user_id': '88382b', 'user_name': 'Cathy Bloom', 'is_blocked': False, 'email_address': 'cathy.bloom@florals.org', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': '321ad39b-75d2-480b-8f91-463f83addd2e', 'account_id': 'cultpass', 'external_user_id': '888fb2', 'user_name': 'David Noir', 'is_blocked': True, 'email_address': 'david.noir@shadowmail.com', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': '3b595166-b4e9-42c4-bd40-f943d6dfa7c6', 'account_id': 'cultpass', 'external_user_id': 'f1f10d', 'user_name': 'Eva Green', 'is_blocked': False, 'email_address': 'eva.green@ecosoul.net', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'user_id': '4bd1e79a-c7d3-4766-9700-fefc403c1906', 'account_id': 'cultpass', 'external_user_id': 'e6376d', 'user_name': 'Frank Ocean', 'is_blocked': False, 'email_address': 'frank.ocean@seawaves.io', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}

In [32]:
with get_session(engine) as session:
    tickets = session.query(udahub.Ticket).all()
    for ticket in tickets:
        # Get all column names for this model
        inst = inspect(ticket)
        # Create a dictionary of {column_name: value}
        columns_data = {c.key: getattr(ticket, c.key) for c in inst.mapper.column_attrs}
        print(columns_data)

{'ticket_id': '6ad49501-5722-4ec6-b4eb-848799e95150', 'account_id': 'cultpass', 'user_id': '7b27662a-1f61-4663-9bfa-6f39269a7ddb', 'channel': 'web', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '2d46f5ea-c53e-47d9-afeb-7df703f6e455', 'account_id': 'cultpass', 'user_id': 'd6eaf64c-9f26-4c67-9918-c97f20330e86', 'channel': 'email', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '7c11bc21-7e46-48fe-854b-15f093228717', 'account_id': 'cultpass', 'user_id': '4b932f2a-677d-4e77-97d1-c071bdb75016', 'channel': 'phone', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '491c6bb0-deb1-4ce1-9323-a24ed0ef69b9', 'account_id': 'cultpass', 'user_id': '7ef9b575-dc02-48ce-a78d-7fb8837ff1ab', 'channel': 'chat', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '7cc40bfb-0850-4b95-8a54-3a9b36fa2668', 'account_id': 'cultpass', 'user_id': '664a6666-dc03-4072-a458-f0ca3e28dd56', 'channel': 'web', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'c51c1b60-4d1a-48ec-bd22-c354875c7103', 'account_id': 'cultpass', 'user_id': '251b2411-0560-4e0d-a440-f02d5394ce2b', 'channel': 'email', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'bd5e42c7-9781-4a26-af34-67516c634e66', 'account_id': 'cultpass', 'user_id': '0ddabea8-4ba1-4982-b346-c605e6444e4f', 'channel': 'phone', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'b4b3ed9e-533f-4906-bd4e-2b6d2b92975b', 'account_id': 'cultpass', 'user_id': '26e0c69d-0779-4014-b9c1-100f60d27ac8', 'channel': 'social', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '728ef485-34d5-4bd5-97f2-98b49a17f8ba', 'account_id': 'cultpass', 'user_id': '635577fd-ecfe-4ff8-a72b-b3e59b30f5ce', 'channel': 'web', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'ea88ddef-04a7-468c-99d9-197da45110b8', 'account_id': 'cultpass', 'user_id': 'c84a759d-1c47-40c2-be90-75edef2092b4', 'channel': 'email', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '4c083d6b-2beb-4ae5-b868-26b26052a975', 'account_id': 'cultpass', 'user_id': '9c0ff72b-a651-4900-a3df-0562bb077eb7', 'channel': 'chat', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '67815915-e32a-48a7-8b92-dba000528560', 'account_id': 'cultpass', 'user_id': 'c0f78c0e-13ae-414f-b8be-058208864426', 'channel': 'web', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'da570e77-8185-4416-a69d-0bfc84e4a3a6', 'account_id': 'cultpass', 'user_id': 'f6fae971-94ef-4577-9327-0b645ea7a577', 'channel': 'phone', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '649b3d3f-3afd-431d-b3c5-108fffe74a6f', 'account_id': 'cultpass', 'user_id': 'dc2ebb67-26d3-4fe9-8277-b2f0488402f3', 'channel': 'email', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'ea569a0f-6f10-4f7f-8461-bf897f551a8d', 'account_id': 'cultpass', 'user_id': '2519e41d-88ef-4772-996e-723b93e63ecd', 'channel': 'chat', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'e867f83e-e19f-4a6a-b479-070c8020bc49', 'account_id': 'cultpass', 'user_id': '797faa2f-7444-4a01-867c-de7cdf30446a', 'channel': 'social', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '6514f64e-7088-4ab4-aa37-0325aed93765', 'account_id': 'cultpass', 'user_id': 'd73380dd-efa5-4b96-8c69-878229f31ee5', 'channel': 'web', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '3d837718-dd00-406d-ac27-59d86c06da00', 'account_id': 'cultpass', 'user_id': 'fbcb5b61-caca-424a-b6bd-e3dc67b83759', 'channel': 'email', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '7b26ec13-d75a-4228-a1b1-e4b7282c1cdf', 'account_id': 'cultpass', 'user_id': '4cabbfb0-2e06-40b4-a158-e5072e766509', 'channel': 'chat', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'b9f6bce6-10c6-4efb-96af-c0f29ce8efce', 'account_id': 'cultpass', 'user_id': 'd8a96610-f8bc-4eeb-ad23-48650ed1d85c', 'channel': 'social', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'a8eae3ee-f06e-40ab-bfc6-227b929a7583', 'account_id': 'cultpass', 'user_id': 'e8c8e4c7-51b0-4cca-abbe-543ddb497345', 'channel': 'web', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'e178fa79-9cc2-4283-afc7-02df71439b9c', 'account_id': 'cultpass', 'user_id': 'b57379ca-187e-441f-b495-96e2edb67429', 'channel': 'email', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '7fbc7fbf-9400-4973-a94d-731e28abb650', 'account_id': 'cultpass', 'user_id': '321ad39b-75d2-480b-8f91-463f83addd2e', 'channel': 'chat', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'c3bf36c6-a983-431b-8fb6-32ac35c5bfbe', 'account_id': 'cultpass', 'user_id': '3b595166-b4e9-42c4-bd40-f943d6dfa7c6', 'channel': 'social', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '6059736d-3965-4eff-99e0-03df65458316', 'account_id': 'cultpass', 'user_id': '4bd1e79a-c7d3-4766-9700-fefc403c1906', 'channel': 'web', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'c6754510-5962-4d10-a4f4-4aef4b960874', 'account_id': 'cultpass', 'user_id': '7b27662a-1f61-4663-9bfa-6f39269a7ddb', 'channel': 'email', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'b764fb71-5b15-4d55-837a-7fa73ed42571', 'account_id': 'cultpass', 'user_id': 'd6eaf64c-9f26-4c67-9918-c97f20330e86', 'channel': 'chat', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'd80eadd1-acd2-4843-a6c9-90bb1173439e', 'account_id': 'cultpass', 'user_id': '4b932f2a-677d-4e77-97d1-c071bdb75016', 'channel': 'social', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '9cc5709b-3b75-42c7-bb9e-d381fc0d1329', 'account_id': 'cultpass', 'user_id': '7ef9b575-dc02-48ce-a78d-7fb8837ff1ab', 'channel': 'web', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '756e8462-fa20-4513-8af5-870b9605c94f', 'account_id': 'cultpass', 'user_id': '664a6666-dc03-4072-a458-f0ca3e28dd56', 'channel': 'email', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '11ecab98-68dd-4809-a319-5b0c7450f5b9', 'account_id': 'cultpass', 'user_id': '251b2411-0560-4e0d-a440-f02d5394ce2b', 'channel': 'chat', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'cc5208a8-ffef-48ae-8d0f-9154e9c265e7', 'account_id': 'cultpass', 'user_id': '0ddabea8-4ba1-4982-b346-c605e6444e4f', 'channel': 'social', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '801134b8-2327-42e6-b994-e8c32a575d8c', 'account_id': 'cultpass', 'user_id': '26e0c69d-0779-4014-b9c1-100f60d27ac8', 'channel': 'web', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'e1a9d192-790c-4bab-ba83-4fb45fcb4afd', 'account_id': 'cultpass', 'user_id': '635577fd-ecfe-4ff8-a72b-b3e59b30f5ce', 'channel': 'email', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '1313ffd3-8c0c-47a9-85ff-a46493d0074e', 'account_id': 'cultpass', 'user_id': 'c84a759d-1c47-40c2-be90-75edef2092b4', 'channel': 'chat', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '2ba290b2-0179-4081-bd4a-a40ef8eb21fd', 'account_id': 'cultpass', 'user_id': '9c0ff72b-a651-4900-a3df-0562bb077eb7', 'channel': 'social', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '92524728-352d-46f4-802e-83151430944b', 'account_id': 'cultpass', 'user_id': 'c0f78c0e-13ae-414f-b8be-058208864426', 'channel': 'web', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '6fba06c2-b9c8-430d-8133-1534ab84fef4', 'account_id': 'cultpass', 'user_id': 'f6fae971-94ef-4577-9327-0b645ea7a577', 'channel': 'email', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'd0d924c1-6394-4c30-832f-7f0eb99387af', 'account_id': 'cultpass', 'user_id': 'dc2ebb67-26d3-4fe9-8277-b2f0488402f3', 'channel': 'chat', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '543a9e78-6b8d-4869-a32d-d7958e346153', 'account_id': 'cultpass', 'user_id': '2519e41d-88ef-4772-996e-723b93e63ecd', 'channel': 'social', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'beb0f868-859e-40fd-bc6e-3364ce2f86e8', 'account_id': 'cultpass', 'user_id': '797faa2f-7444-4a01-867c-de7cdf30446a', 'channel': 'web', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '3e92a42e-03d3-44d9-82ae-831373ba6c18', 'account_id': 'cultpass', 'user_id': 'd73380dd-efa5-4b96-8c69-878229f31ee5', 'channel': 'email', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '727975b1-3b93-495e-9ae5-307bed978656', 'account_id': 'cultpass', 'user_id': 'fbcb5b61-caca-424a-b6bd-e3dc67b83759', 'channel': 'chat', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'a0bedc33-f62e-46e3-8a6e-65e75050f477', 'account_id': 'cultpass', 'user_id': '4cabbfb0-2e06-40b4-a158-e5072e766509', 'channel': 'social', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'ef8fa011-4811-4722-a93d-7ce99a387ccc', 'account_id': 'cultpass', 'user_id': 'd8a96610-f8bc-4eeb-ad23-48650ed1d85c', 'channel': 'web', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '7f68a856-affa-40fa-a749-c74d15bdceb2', 'account_id': 'cultpass', 'user_id': 'e8c8e4c7-51b0-4cca-abbe-543ddb497345', 'channel': 'email', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '84df24b2-17a9-4279-bc60-f359d1d9f913', 'account_id': 'cultpass', 'user_id': 'b57379ca-187e-441f-b495-96e2edb67429', 'channel': 'chat', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '3843b239-a1da-4784-9147-6e25976f15de', 'account_id': 'cultpass', 'user_id': '321ad39b-75d2-480b-8f91-463f83addd2e', 'channel': 'social', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'ba7b6253-3bd0-4ec3-87e9-b301faf68db8', 'account_id': 'cultpass', 'user_id': '3b595166-b4e9-42c4-bd40-f943d6dfa7c6', 'channel': 'web', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '495cf6e3-5031-46c1-a7fa-3c0d4b16f404', 'account_id': 'cultpass', 'user_id': '4bd1e79a-c7d3-4766-9700-fefc403c1906', 'channel': 'email', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}

In [33]:
with get_session(engine) as session:
    messages = session.query(udahub.TicketMessage).all()
    for message in messages:
        # Get all column names for this model
        inst = inspect(message)
        # Create a dictionary of {column_name: value}
        columns_data = {c.key: getattr(message, c.key) for c in inst.mapper.column_attrs}
        print(columns_data)

{'message_id': '3f37692b-a897-4ca0-999d-c4e60a0f2915', 'ticket_id': '6ad49501-5722-4ec6-b4eb-848799e95150', 'role': <RoleEnum.user: 'user'>, 'content': "Hi there, I am trying to book a flight through your website, but I keep getting an error message when I try to enter my payment details. I've tried multiple times and even used different browsers, but the issue persists. Could you please assist me with this? Thank you!", 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'e3af6f84-a621-40a3-9757-35db251c590a', 'ticket_id': '2d46f5ea-c53e-47d9-afeb-7df703f6e455', 'role': <RoleEnum.user: 'user'>, 'content': "Hello, I forgot my password and am unable to access my account. I tried the 'forgot password' option, but I haven't received any reset email. Can you help me regain access to my account?", 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '6856cef3-2dcf-4320-a9a0-282b3f5eb77b', 'ticket_id': '7c11bc21-7e46-48fe-854b-15f093228717', 'role': <RoleEnum.user: 'user'>, 'content': 'I need to escalate an issue regarding my hotel reservation. I was promised a sea view room, but upon arrival, I was given a standard room. This is not acceptable, and I would like this matter resolved immediately.', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '91f346fc-b636-4036-839c-92420e7df5e0', 'ticket_id': '491c6bb0-deb1-4ce1-9323-a24ed0ef69b9', 'role': <RoleEnum.user: 'user'>, 'content': 'Hi, I am unable to access the premium features of my account even though I have a valid subscription. Could you please look into this and resolve the issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'f8777059-4097-499a-ad03-4e74d2fc2e48', 'ticket_id': '7cc40bfb-0850-4b95-8a54-3a9b36fa2668', 'role': <RoleEnum.user: 'user'>, 'content': "Hello, I am trying to pause my gym membership for a month due to personal reasons. However, I can't find the option to do so on your website. Can you guide me through the process?", 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'bdf92b9f-764d-4a85-9c9c-4798dc5d950b', 'ticket_id': 'c51c1b60-4d1a-48ec-bd22-c354875c7103', 'role': <RoleEnum.user: 'user'>, 'content': 'I have a question regarding the attendance policy for the upcoming conference. Is it mandatory to attend all sessions, or can we choose specific ones?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '69fb1d1e-7079-4a7e-a36b-dbbb43b5c73f', 'ticket_id': 'bd5e42c7-9781-4a26-af34-67516c634e66', 'role': <RoleEnum.user: 'user'>, 'content': 'Hi, I am trying to make a reservation at your restaurant, but the pricing seems to be different from what was advertised. Can you clarify the correct pricing for me?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '84b9788b-446e-46cc-a74a-3922f8831853', 'ticket_id': 'b4b3ed9e-533f-4906-bd4e-2b6d2b92975b', 'role': <RoleEnum.user: 'user'>, 'content': 'I am interested in knowing more about the benefits included in the premium package. Could you provide me with detailed information?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '84c36642-200e-4e27-babc-d542ef76b869', 'ticket_id': '728ef485-34d5-4bd5-97f2-98b49a17f8ba', 'role': <RoleEnum.user: 'user'>, 'content': 'Hello, I am trying to book tickets for an event, but the website keeps crashing. Is there an alternative way to book the tickets?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '8d21acb7-3550-4d27-9390-875d3fa638d2', 'ticket_id': 'ea88ddef-04a7-468c-99d9-197da45110b8', 'role': <RoleEnum.user: 'user'>, 'content': "I am unable to log in to my account. I have tried resetting my password, but it still doesn't work. Can you help me resolve this issue?", 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '822f261b-688e-4715-b22f-8db215dc5380', 'ticket_id': '4c083d6b-2beb-4ae5-b868-26b26052a975', 'role': <RoleEnum.user: 'user'>, 'content': 'Hi, I am considering upgrading my subscription, but I would like to know more about the benefits included in the higher tier. Can you provide me with more information?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'e65ffedc-4cfa-4645-8986-dbcb00ed6afa', 'ticket_id': '67815915-e32a-48a7-8b92-dba000528560', 'role': <RoleEnum.user: 'user'>, 'content': 'I am trying to cancel my reservation, but the option is not available on the website. Can you assist me with the cancellation process?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'e23bb765-4131-4c57-bbbf-4cbc05863746', 'ticket_id': 'da570e77-8185-4416-a69d-0bfc84e4a3a6', 'role': <RoleEnum.user: 'user'>, 'content': 'Hello, I am having trouble with my subscription. I was charged twice for the same month. Can you look into this and refund the extra charge?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'e28e6221-d361-41ec-8385-00b7230b6d3d', 'ticket_id': '649b3d3f-3afd-431d-b3c5-108fffe74a6f', 'role': <RoleEnum.user: 'user'>, 'content': 'I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '660e1687-d8e0-4280-b718-cae317533a9c', 'ticket_id': 'ea569a0f-6f10-4f7f-8461-bf897f551a8d', 'role': <RoleEnum.user: 'user'>, 'content': 'Hi, I am trying to log in to my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '076ee607-de58-4d09-b5f5-2079d662786c', 'ticket_id': 'e867f83e-e19f-4a6a-b479-070c8020bc49', 'role': <RoleEnum.user: 'user'>, 'content': 'I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '9e875a18-7088-429f-b665-3bf903c41361', 'ticket_id': '6514f64e-7088-4ab4-aa37-0325aed93765', 'role': <RoleEnum.user: 'user'>, 'content': 'Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'e39776a1-13a3-4394-89dc-02c9a0849776', 'ticket_id': '3d837718-dd00-406d-ac27-59d86c06da00', 'role': <RoleEnum.user: 'user'>, 'content': 'I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'ddc87227-fb78-4556-a217-5f0333ffba8d', 'ticket_id': '7b26ec13-d75a-4228-a1b1-e4b7282c1cdf', 'role': <RoleEnum.user: 'user'>, 'content': 'Hi, I am trying to access my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '6f33884d-0bb8-48d2-9490-11fd77dbe134', 'ticket_id': 'b9f6bce6-10c6-4efb-96af-c0f29ce8efce', 'role': <RoleEnum.user: 'user'>, 'content': 'I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'cb4897dd-5fb8-4e18-8914-b59c0a4c3d8c', 'ticket_id': 'a8eae3ee-f06e-40ab-bfc6-227b929a7583', 'role': <RoleEnum.user: 'user'>, 'content': 'Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '7b243d66-32a6-43d3-9ad3-571f3260478a', 'ticket_id': 'e178fa79-9cc2-4283-afc7-02df71439b9c', 'role': <RoleEnum.user: 'user'>, 'content': 'I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '1166cd5e-8327-4113-bad1-f464f40f929e', 'ticket_id': '7fbc7fbf-9400-4973-a94d-731e28abb650', 'role': <RoleEnum.user: 'user'>, 'content': 'Hi, I am trying to log in to my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'cd665681-9229-4709-94eb-01884326cffd', 'ticket_id': 'c3bf36c6-a983-431b-8fb6-32ac35c5bfbe', 'role': <RoleEnum.user: 'user'>, 'content': 'I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '5b453b0c-fbce-4e38-958d-644241184395', 'ticket_id': '6059736d-3965-4eff-99e0-03df65458316', 'role': <RoleEnum.user: 'user'>, 'content': 'Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'e2135be2-800c-4441-b032-5fe9cdaf27d1', 'ticket_id': 'c6754510-5962-4d10-a4f4-4aef4b960874', 'role': <RoleEnum.user: 'user'>, 'content': 'I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '4457eced-b42f-4a0b-a82d-c186a3c5bdc2', 'ticket_id': 'b764fb71-5b15-4d55-837a-7fa73ed42571', 'role': <RoleEnum.user: 'user'>, 'content': 'Hi, I am trying to log in to my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '405ffe03-08e2-441f-89d2-82dc198d3c3c', 'ticket_id': 'd80eadd1-acd2-4843-a6c9-90bb1173439e', 'role': <RoleEnum.user: 'user'>, 'content': 'I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '9686cd22-479c-40b5-ac30-a9b839a225d5', 'ticket_id': '9cc5709b-3b75-42c7-bb9e-d381fc0d1329', 'role': <RoleEnum.user: 'user'>, 'content': 'Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '049bcfef-5a38-495e-bca2-9edb4aad52b7', 'ticket_id': '756e8462-fa20-4513-8af5-870b9605c94f', 'role': <RoleEnum.user: 'user'>, 'content': 'I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '5eeb5805-54e8-4cb8-bc90-ed7c7c9cb961', 'ticket_id': '11ecab98-68dd-4809-a319-5b0c7450f5b9', 'role': <RoleEnum.user: 'user'>, 'content': 'Hi, I am trying to log in to my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'ed736386-5f32-454e-9fa6-1d3100a45635', 'ticket_id': 'cc5208a8-ffef-48ae-8d0f-9154e9c265e7', 'role': <RoleEnum.user: 'user'>, 'content': 'I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '8d9c0a2a-4687-4895-abd2-ba3a82fd8acb', 'ticket_id': '801134b8-2327-42e6-b994-e8c32a575d8c', 'role': <RoleEnum.user: 'user'>, 'content': 'Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '9aca8682-8dac-45f2-bb81-f3545f8343d1', 'ticket_id': 'e1a9d192-790c-4bab-ba83-4fb45fcb4afd', 'role': <RoleEnum.user: 'user'>, 'content': 'I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '91f4cccc-cfa3-4ac5-911a-a11bf0f7261b', 'ticket_id': '1313ffd3-8c0c-47a9-85ff-a46493d0074e', 'role': <RoleEnum.user: 'user'>, 'content': 'Hi, I am trying to log in to my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'b6e3384c-dc08-410c-a7fa-9d3e00f471fd', 'ticket_id': '2ba290b2-0179-4081-bd4a-a40ef8eb21fd', 'role': <RoleEnum.user: 'user'>, 'content': 'I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '0d777554-4552-4435-a49f-6e80419547a8', 'ticket_id': '92524728-352d-46f4-802e-83151430944b', 'role': <RoleEnum.user: 'user'>, 'content': 'Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '299e2b32-f447-45ca-807e-ee951cfe8017', 'ticket_id': '6fba06c2-b9c8-430d-8133-1534ab84fef4', 'role': <RoleEnum.user: 'user'>, 'content': 'I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'a49d56c3-d203-457b-8265-278d55dcae20', 'ticket_id': 'd0d924c1-6394-4c30-832f-7f0eb99387af', 'role': <RoleEnum.user: 'user'>, 'content': 'Hi, I am trying to log in to my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'd8db412d-44fc-412f-8d7d-188608a4560d', 'ticket_id': '543a9e78-6b8d-4869-a32d-d7958e346153', 'role': <RoleEnum.user: 'user'>, 'content': 'I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'f200b153-1c12-4f28-8920-75884880ce3b', 'ticket_id': 'beb0f868-859e-40fd-bc6e-3364ce2f86e8', 'role': <RoleEnum.user: 'user'>, 'content': 'Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '92cb9bf5-5273-4cc1-88d8-6ad80d55d6d2', 'ticket_id': '3e92a42e-03d3-44d9-82ae-831373ba6c18', 'role': <RoleEnum.user: 'user'>, 'content': 'I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'fe9fa266-f2e9-4ad8-89fe-af79cebe3ce5', 'ticket_id': '727975b1-3b93-495e-9ae5-307bed978656', 'role': <RoleEnum.user: 'user'>, 'content': 'Hi, I am trying to log in to my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'ed97c041-9e08-45d7-99c5-2cc8807a8059', 'ticket_id': 'a0bedc33-f62e-46e3-8a6e-65e75050f477', 'role': <RoleEnum.user: 'user'>, 'content': 'I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'abcdff41-0635-4411-8880-4d032c7f3e8f', 'ticket_id': 'ef8fa011-4811-4722-a93d-7ce99a387ccc', 'role': <RoleEnum.user: 'user'>, 'content': 'Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'e7ada99e-a195-4386-a899-080f2896d762', 'ticket_id': '7f68a856-affa-40fa-a749-c74d15bdceb2', 'role': <RoleEnum.user: 'user'>, 'content': 'I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'a152d0df-b291-4d0d-b5da-953d9b30fecc', 'ticket_id': '84df24b2-17a9-4279-bc60-f359d1d9f913', 'role': <RoleEnum.user: 'user'>, 'content': 'Hi, I am trying to log in to my account, but it says my credentials are incorrect. I am sure I am entering the correct details. Can you help me resolve this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': '67e59e72-8428-448f-af54-98d8e47541d1', 'ticket_id': '3843b239-a1da-4784-9147-6e25976f15de', 'role': <RoleEnum.user: 'user'>, 'content': 'I am interested in attending the upcoming event, but I am not sure about the schedule. Can you provide me with the event details?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'bb2cb435-fcf7-47a1-abf2-5af6e11bd689', 'ticket_id': 'ba7b6253-3bd0-4ec3-87e9-b301faf68db8', 'role': <RoleEnum.user: 'user'>, 'content': 'Hello, I am trying to book a hotel room, but the website is not loading properly. Is there another way to make the booking?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'message_id': 'd75c4021-0fee-4eef-89bd-3e76b4a162bd', 'ticket_id': '495cf6e3-5031-46c1-a7fa-3c0d4b16f404', 'role': <RoleEnum.user: 'user'>, 'content': 'I am unable to access the benefits section of my account. It keeps showing an error message. Can you help me fix this issue?', 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}

In [35]:
with get_session(engine) as session:
    metas = session.query(udahub.TicketMetadata).all()
    for meta in metas:
        # Get all column names for this model
        inst = inspect(meta)
        # Create a dictionary of {column_name: value}
        columns_data = {c.key: getattr(meta, c.key) for c in inst.mapper.column_attrs}
        print(columns_data)

{'ticket_id': '6ad49501-5722-4ec6-b4eb-848799e95150', 'status': 'open', 'main_issue_type': None, 'tags': 'booking', 'urgency_score': 0.6913808257333285, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '2d46f5ea-c53e-47d9-afeb-7df703f6e455', 'status': 'open', 'main_issue_type': None, 'tags': 'password', 'urgency_score': 0.0816098239646863, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '7c11bc21-7e46-48fe-854b-15f093228717', 'status': 'open', 'main_issue_type': None, 'tags': 'escalation', 'urgency_score': 0.151781007667947, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '491c6bb0-deb1-4ce1-9323-a24ed0ef69b9', 'status': 'open', 'main_issue_type': None, 'tags': 'access', 'urgency_score': 0.6117001329742916, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '7cc40bfb-0850-4b95-8a54-3a9b36fa2668', 'status': 'open', 'main_issue_type': None, 'tags': 'pause', 'urgency_score': 0.866804887593044, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'c51c1b60-4d1a-48ec-bd22-c354875c7103', 'status': 'open', 'main_issue_type': None, 'tags': 'attendance', 'urgency_score': 0.8954328768326866, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'bd5e42c7-9781-4a26-af34-67516c634e66', 'status': 'open', 'main_issue_type': None, 'tags': 'reservation', 'urgency_score': 0.8156640669269484, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'b4b3ed9e-533f-4906-bd4e-2b6d2b92975b', 'status': 'open', 'main_issue_type': None, 'tags': 'benefits', 'urgency_score': 0.6015061880897035, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '728ef485-34d5-4bd5-97f2-98b49a17f8ba', 'status': 'open', 'main_issue_type': None, 'tags': 'booking', 'urgency_score': 0.4323676156655121, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'ea88ddef-04a7-468c-99d9-197da45110b8', 'status': 'open', 'main_issue_type': None, 'tags': 'login', 'urgency_score': 0.7517009912096524, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '4c083d6b-2beb-4ae5-b868-26b26052a975', 'status': 'open', 'main_issue_type': None, 'tags': 'benefits', 'urgency_score': 0.7248500901724806, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '67815915-e32a-48a7-8b92-dba000528560', 'status': 'open', 'main_issue_type': None, 'tags': 'cancelation', 'urgency_score': 0.7811405486623516, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'da570e77-8185-4416-a69d-0bfc84e4a3a6', 'status': 'open', 'main_issue_type': None, 'tags': 'subscription', 'urgency_score': 0.6115352312131227, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '649b3d3f-3afd-431d-b3c5-108fffe74a6f', 'status': 'open', 'main_issue_type': None, 'tags': 'benefits', 'urgency_score': 0.271750078860883, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'ea569a0f-6f10-4f7f-8461-bf897f551a8d', 'status': 'open', 'main_issue_type': None, 'tags': 'login', 'urgency_score': 0.9384755052211529, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'e867f83e-e19f-4a6a-b479-070c8020bc49', 'status': 'open', 'main_issue_type': None, 'tags': 'events', 'urgency_score': 0.44989297527219374, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '6514f64e-7088-4ab4-aa37-0325aed93765', 'status': 'open', 'main_issue_type': None, 'tags': 'booking', 'urgency_score': 0.18792302396059934, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '3d837718-dd00-406d-ac27-59d86c06da00', 'status': 'open', 'main_issue_type': None, 'tags': 'benefits', 'urgency_score': 0.2622522299348993, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '7b26ec13-d75a-4228-a1b1-e4b7282c1cdf', 'status': 'open', 'main_issue_type': None, 'tags': 'access', 'urgency_score': 0.3852736012133392, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'b9f6bce6-10c6-4efb-96af-c0f29ce8efce', 'status': 'open', 'main_issue_type': None, 'tags': 'events', 'urgency_score': 0.05408080931531034, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'a8eae3ee-f06e-40ab-bfc6-227b929a7583', 'status': 'open', 'main_issue_type': None, 'tags': 'booking', 'urgency_score': 0.6831170412502794, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'e178fa79-9cc2-4283-afc7-02df71439b9c', 'status': 'open', 'main_issue_type': None, 'tags': 'benefits', 'urgency_score': 0.06384823707197285, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '7fbc7fbf-9400-4973-a94d-731e28abb650', 'status': 'open', 'main_issue_type': None, 'tags': 'login', 'urgency_score': 0.2702668189336219, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'c3bf36c6-a983-431b-8fb6-32ac35c5bfbe', 'status': 'open', 'main_issue_type': None, 'tags': 'events', 'urgency_score': 0.8422661462793383, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '6059736d-3965-4eff-99e0-03df65458316', 'status': 'open', 'main_issue_type': None, 'tags': 'booking', 'urgency_score': 0.42263334359866245, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'c6754510-5962-4d10-a4f4-4aef4b960874', 'status': 'open', 'main_issue_type': None, 'tags': 'benefits', 'urgency_score': 0.5158106866236728, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'b764fb71-5b15-4d55-837a-7fa73ed42571', 'status': 'open', 'main_issue_type': None, 'tags': 'login', 'urgency_score': 0.9171779477519535, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'd80eadd1-acd2-4843-a6c9-90bb1173439e', 'status': 'open', 'main_issue_type': None, 'tags': 'events', 'urgency_score': 0.7557617877547347, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '9cc5709b-3b75-42c7-bb9e-d381fc0d1329', 'status': 'open', 'main_issue_type': None, 'tags': 'booking', 'urgency_score': 0.9898619086710077, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '756e8462-fa20-4513-8af5-870b9605c94f', 'status': 'open', 'main_issue_type': None, 'tags': 'benefits', 'urgency_score': 0.9047263466840919, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '11ecab98-68dd-4809-a319-5b0c7450f5b9', 'status': 'open', 'main_issue_type': None, 'tags': 'login', 'urgency_score': 0.1782702485706985, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'cc5208a8-ffef-48ae-8d0f-9154e9c265e7', 'status': 'open', 'main_issue_type': None, 'tags': 'events', 'urgency_score': 0.11926008361913831, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '801134b8-2327-42e6-b994-e8c32a575d8c', 'status': 'open', 'main_issue_type': None, 'tags': 'booking', 'urgency_score': 0.22425450641413525, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'e1a9d192-790c-4bab-ba83-4fb45fcb4afd', 'status': 'open', 'main_issue_type': None, 'tags': 'benefits', 'urgency_score': 0.4671169040215045, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '1313ffd3-8c0c-47a9-85ff-a46493d0074e', 'status': 'open', 'main_issue_type': None, 'tags': 'login', 'urgency_score': 0.41375087764421703, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '2ba290b2-0179-4081-bd4a-a40ef8eb21fd', 'status': 'open', 'main_issue_type': None, 'tags': 'events', 'urgency_score': 0.3159106974987693, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '92524728-352d-46f4-802e-83151430944b', 'status': 'open', 'main_issue_type': None, 'tags': 'booking', 'urgency_score': 0.8868405742574256, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '6fba06c2-b9c8-430d-8133-1534ab84fef4', 'status': 'open', 'main_issue_type': None, 'tags': 'benefits', 'urgency_score': 0.4188371437765305, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'd0d924c1-6394-4c30-832f-7f0eb99387af', 'status': 'open', 'main_issue_type': None, 'tags': 'login', 'urgency_score': 0.490015352965963, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '543a9e78-6b8d-4869-a32d-d7958e346153', 'status': 'open', 'main_issue_type': None, 'tags': 'events', 'urgency_score': 0.9833692039457544, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'beb0f868-859e-40fd-bc6e-3364ce2f86e8', 'status': 'open', 'main_issue_type': None, 'tags': 'booking', 'urgency_score': 0.7256675867739097, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '3e92a42e-03d3-44d9-82ae-831373ba6c18', 'status': 'open', 'main_issue_type': None, 'tags': 'benefits', 'urgency_score': 0.7743582262596224, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '727975b1-3b93-495e-9ae5-307bed978656', 'status': 'open', 'main_issue_type': None, 'tags': 'login', 'urgency_score': 0.8993946635240325, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'a0bedc33-f62e-46e3-8a6e-65e75050f477', 'status': 'open', 'main_issue_type': None, 'tags': 'events', 'urgency_score': 0.08385823802652193, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'ef8fa011-4811-4722-a93d-7ce99a387ccc', 'status': 'open', 'main_issue_type': None, 'tags': 'booking', 'urgency_score': 0.5249487185241187, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '7f68a856-affa-40fa-a749-c74d15bdceb2', 'status': 'open', 'main_issue_type': None, 'tags': 'benefits', 'urgency_score': 0.8624164666022551, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '84df24b2-17a9-4279-bc60-f359d1d9f913', 'status': 'open', 'main_issue_type': None, 'tags': 'login', 'urgency_score': 0.044737586627266124, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '3843b239-a1da-4784-9147-6e25976f15de', 'status': 'open', 'main_issue_type': None, 'tags': 'events', 'urgency_score': 0.3343152859143633, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': 'ba7b6253-3bd0-4ec3-87e9-b301faf68db8', 'status': 'open', 'main_issue_type': None, 'tags': 'booking', 'urgency_score': 0.4764228711765538, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}
{'ticket_id': '495cf6e3-5031-46c1-a7fa-3c0d4b16f404', 'status': 'open', 'main_issue_type': None, 'tags': 'benefits', 'urgency_score': 0.33748206308579576, 'created_at': datetime.datetime(2026, 4, 5, 11, 43, 46), 'updated_at': datetime.datetime(2026, 4, 5, 11, 43, 46)}

In [34]:
with get_session(engine) as session:
    user = session.query(udahub.User).filter_by(
        account_id=account_id,
        external_user_id=ticket_table.iloc[2].to_dict()["owner_id"],
    ).first()
    
    ticket:udahub.Ticket = user.tickets[0]
    for message in ticket.messages:
        print(message)

<TicketMessage(message_id='6856cef3-2dcf-4320-a9a0-282b3f5eb77b', role='user', content='I need to escalate an issue re...')>